export const MENU_CATEGORIES = [
	{ id: 'appetizers', name: 'المقبلات', nameEn: 'Appetizers', icon: '🥗', order: 1 },
	{ id: 'mains', name: 'الأطباق الرئيسية', nameEn: 'Mains', icon: '🍖', order: 2 },
	{ id: 'grills', name: 'المشاوي', nameEn: 'Grills', icon: '🔥', order: 3 },
	{ id: 'seafood', name: 'المأكولات البحرية', nameEn: 'Seafood', icon: '🦐', order: 4 },
	{ id: 'drinks', name: 'المشروبات', nameEn: 'Drinks', icon: '🥤', order: 5 },
	{ id: 'desserts', name: 'الحلويات', nameEn: 'Desserts', icon: '🍰', order: 6 },
];

export const MODIFIER_GROUPS = {
	spiciness: {
		id: 'spiciness',
		name: 'الحرارة',
		nameEn: 'Spice level',
		type: 'single',
		required: false,
		options: [
			{ id: 'mild', name: 'خفيفة', nameEn: 'Mild', price: 0 },
			{ id: 'medium', name: 'متوسطة', nameEn: 'Medium', price: 0 },
			{ id: 'hot', name: 'حارة', nameEn: 'Hot', price: 0 },
			{ id: 'extra', name: 'حارة جداً', nameEn: 'Extra hot', price: 2 },
		],
	},
	extras: {
		id: 'extras',
		name: 'إضافات',
		nameEn: 'Extras',
		type: 'multiple',
		required: false,
		options: [
			{ id: 'cheese', name: 'جبنة إضافية', nameEn: 'Extra cheese', price: 5 },
			{ id: 'sauce', name: 'صوص إضافي', nameEn: 'Extra sauce', price: 3 },
			{ id: 'garlic', name: 'ثوم', nameEn: 'Garlic', price: 2 },
			{ id: 'nuts', name: 'مكسرات', nameEn: 'Nuts', price: 4 },
		],
	},
	size: {
		id: 'size',
		name: 'الحجم',
		nameEn: 'Size',
		type: 'single',
		required: true,
		options: [
			{ id: 'small', name: 'صغير', nameEn: 'Small', price: 0 },
			{ id: 'medium', name: 'متوسط', nameEn: 'Medium', price: 5 },
			{ id: 'large', name: 'كبير', nameEn: 'Large', price: 10 },
		],
	},
	sides: {
		id: 'sides',
		name: 'المرافق',
		nameEn: 'Sides',
		type: 'multiple',
		required: false,
		options: [
			{ id: 'rice', name: 'أرز', nameEn: 'Rice', price: 8 },
			{ id: 'bread', name: 'خبز', nameEn: 'Bread', price: 3 },
			{ id: 'salad', name: 'سلطة', nameEn: 'Salad', price: 10 },
			{ id: 'fries', name: 'بطاطس', nameEn: 'Fries', price: 12 },
		],
	},
};

// Dummy menu. Images are external (Unsplash) for demo purposes.
export const MENU_ITEMS = [
	// Appetizers
	{
		id: 'app1',
		categoryId: 'appetizers',
		name: 'حمص بالصنوبر',
		nameEn: 'Hummus with Pine Nuts',
		description: 'حمص كريمي مع زيت الزيتون والصنوبر المحمص',
		descriptionEn: 'Creamy hummus topped with olive oil and toasted pine nuts.',
		price: 18,
		image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400&h=400&fit=crop',
		emoji: '🫘',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: true,
		modifiers: ['extras'],
	},
	{
		id: 'app2',
		categoryId: 'appetizers',
		name: 'تبولة',
		nameEn: 'Tabbouleh',
		description: 'سلطة بقدونس طازجة مع الطماطم والبرغل والليمون',
		descriptionEn: 'Fresh parsley salad with tomato, bulgur, and lemon.',
		price: 22,
		image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=400&fit=crop',
		emoji: '🥗',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: true,
		modifiers: ['extras'],
	},
	{
		id: 'app3',
		categoryId: 'appetizers',
		name: 'فلافل',
		nameEn: 'Falafel',
		description: 'كرة فلافل مقرمشة مع الطحينة',
		descriptionEn: 'Crispy falafel balls served with tahini.',
		price: 15,
		image: 'https://images.unsplash.com/photo-1518589681436-7f4d0090b97b?w=400&h=400&fit=crop',
		emoji: '🧆',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: false,
		modifiers: ['extras'],
	},
	{
		id: 'app4',
		categoryId: 'appetizers',
		name: 'متبلات',
		nameEn: 'Pickles',
		description: 'تشكيلة من المخللات الشرقية',
		descriptionEn: 'Assorted Middle Eastern pickles.',
		price: 12,
		image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop',
		emoji: '🥒',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: false,
		modifiers: [],
	},

	// Mains
	{
		id: 'main1',
		categoryId: 'mains',
		name: 'مندي لحم',
		nameEn: 'Lamb Mandi',
		description: 'لحم ضأن طري مع الأرز الباسمتي والتوابل الخاصة',
		descriptionEn: 'Tender lamb mandi with basmati rice and signature spices.',
		price: 65,
		image: 'https://images.unsplash.com/photo-1513185158878-8d8f2a2a3da3?w=400&h=400&fit=crop',
		emoji: '🍖',
		available: true,
		spicy: false,
		vegetarian: false,
		popular: true,
		modifiers: ['size', 'sides'],
	},
	{
		id: 'main2',
		categoryId: 'mains',
		name: 'كبسة دجاج',
		nameEn: 'Chicken Kabsa',
		description: 'أرز كبسة بالدجاج مع اللوز والزبيب',
		descriptionEn: 'Chicken kabsa rice with almonds and raisins.',
		price: 45,
		image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=400&h=400&fit=crop',
		emoji: '🍛',
		available: true,
		spicy: true,
		vegetarian: false,
		popular: true,
		modifiers: ['spiciness', 'sides'],
	},
	{
		id: 'main3',
		categoryId: 'mains',
		name: 'برياني هندي',
		nameEn: 'Indian Biryani',
		description: 'أرز برياني بالدجاج مع الزبادي',
		descriptionEn: 'Chicken biryani rice served with yogurt.',
		price: 42,
		image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=400&fit=crop',
		emoji: '🍚',
		available: true,
		spicy: true,
		vegetarian: false,
		popular: false,
		modifiers: ['spiciness', 'sides'],
	},

	// Grills
	{
		id: 'grill1',
		categoryId: 'grills',
		name: 'شواية مشكل',
		nameEn: 'Mixed Grill',
		description: 'تشكيلة من اللحوم والدجاج والكباب',
		descriptionEn: 'Mixed grill selection of meats, chicken, and kebab.',
		price: 95,
		image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=400&fit=crop',
		emoji: '🥩',
		available: true,
		spicy: false,
		vegetarian: false,
		popular: true,
		modifiers: ['sides'],
	},
	{
		id: 'grill2',
		categoryId: 'grills',
		name: 'شيش طاووق',
		nameEn: 'Shish Tawook',
		description: 'قطع دجاج متبلة بالزبادي والزعفران',
		descriptionEn: 'Yogurt and saffron marinated chicken skewers.',
		price: 48,
		image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=400&fit=crop',
		emoji: '🍢',
		available: true,
		spicy: false,
		vegetarian: false,
		popular: true,
		modifiers: ['sides'],
	},
	{
		id: 'grill3',
		categoryId: 'grills',
		name: 'كباب لحم',
		nameEn: 'Lamb Kebab',
		description: 'كباب لحم ضأن مع البصل والفلفل',
		descriptionEn: 'Lamb kebab with onion and peppers.',
		price: 55,
		image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=400&fit=crop',
		emoji: '🍡',
		available: true,
		spicy: false,
		vegetarian: false,
		popular: false,
		modifiers: ['spiciness', 'sides'],
	},

	// Seafood
	{
		id: 'sea1',
		categoryId: 'seafood',
		name: 'سمك مشوي',
		nameEn: 'Grilled Fish',
		description: 'سمك مشوي بالزعتر والليمون',
		descriptionEn: 'Grilled fish with thyme and lemon.',
		price: 58,
		image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=400&h=400&fit=crop',
		emoji: '🐟',
		available: true,
		spicy: false,
		vegetarian: false,
		popular: true,
		modifiers: ['sides', 'extras'],
	},
	{
		id: 'sea2',
		categoryId: 'seafood',
		name: 'روبيان مقلي',
		nameEn: 'Fried Shrimp',
		description: 'روبيان مقلي مع صلصة الثوم',
		descriptionEn: 'Fried shrimp with garlic sauce.',
		price: 62,
		image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=400&fit=crop',
		emoji: '🦐',
		available: true,
		spicy: false,
		vegetarian: false,
		popular: false,
		modifiers: ['extras'],
	},
	{
		id: 'sea3',
		categoryId: 'seafood',
		name: 'كاليماري',
		nameEn: 'Calamari',
		description: 'حبار مقلي مع صلصة التارتار',
		descriptionEn: 'Fried calamari with tartar sauce.',
		price: 54,
		image: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=400&h=400&fit=crop',
		emoji: '🦑',
		available: true,
		spicy: false,
		vegetarian: false,
		popular: false,
		modifiers: ['extras'],
	},

	// Drinks
	{
		id: 'drink1',
		categoryId: 'drinks',
		name: 'عصير برتقال طازج',
		nameEn: 'Fresh Orange Juice',
		description: 'عصير برتقال طبيعي 100%',
		descriptionEn: '100% fresh orange juice.',
		price: 16,
		image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=400&fit=crop',
		emoji: '🍊',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: true,
		modifiers: ['size'],
	},
	{
		id: 'drink2',
		categoryId: 'drinks',
		name: 'عصير ليمون بالنعناع',
		nameEn: 'Lemon Mint Juice',
		description: 'عصير ليمون منعش مع أوراق النعناع',
		descriptionEn: 'Refreshing lemon juice with mint leaves.',
		price: 14,
		image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400&h=400&fit=crop',
		emoji: '🍋',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: true,
		modifiers: ['size'],
	},
	{
		id: 'drink3',
		categoryId: 'drinks',
		name: 'موهيتو',
		nameEn: 'Mojito',
		description: 'موهيتو كلاسيك بدون كحول',
		descriptionEn: 'Classic non-alcoholic mojito.',
		price: 22,
		image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&h=400&fit=crop',
		emoji: '🥃',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: false,
		modifiers: ['size', 'extras'],
	},
	{
		id: 'drink4',
		categoryId: 'drinks',
		name: 'قهوة عربية',
		nameEn: 'Arabic Coffee',
		description: 'قهوة عربية بالهيل والزعفران',
		descriptionEn: 'Arabic coffee with cardamom and saffron.',
		price: 12,
		image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
		emoji: '☕',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: false,
		modifiers: ['size'],
	},
	{
		id: 'drink5',
		categoryId: 'drinks',
		name: 'شاي كركديه',
		nameEn: 'Hibiscus Tea',
		description: 'شاي كركديه بارد أو ساخن',
		descriptionEn: 'Hibiscus tea, hot or iced.',
		price: 10,
		image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&h=400&fit=crop',
		emoji: '🍵',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: false,
		modifiers: ['size'],
	},

	// Desserts
	{
		id: 'dessert1',
		categoryId: 'desserts',
		name: 'كنافة نابلسية',
		nameEn: 'Nablus Kunafa',
		description: 'كنافة بالجبنة والقطر',
		descriptionEn: 'Kunafa with cheese and syrup.',
		price: 24,
		image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=400&fit=crop',
		emoji: '🥧',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: true,
		modifiers: ['extras'],
	},
	{
		id: 'dessert2',
		categoryId: 'desserts',
		name: 'أم علي',
		nameEn: 'Um Ali',
		description: 'حلوى أم علي بالحليب والمكسرات',
		descriptionEn: 'Um Ali bread pudding with milk and nuts.',
		price: 20,
		image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400&h=400&fit=crop',
		emoji: '🍮',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: false,
		modifiers: ['extras'],
	},
	{
		id: 'dessert3',
		categoryId: 'desserts',
		name: 'بسبوسة',
		nameEn: 'Basbousa',
		description: 'بسبوسة بالقطر',
		descriptionEn: 'Basbousa semolina cake with syrup.',
		price: 16,
		image: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=400&h=400&fit=crop',
		emoji: '🧁',
		available: true,
		spicy: false,
		vegetarian: true,
		popular: false,
		modifiers: ['extras'],
	},
];

export const CATALOG = (() => {
	const byId = new Map();
	for (const item of MENU_ITEMS) byId.set(item.id, item);
	return { byId };
})();
